spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DASH_DATABASE_URL:jdbc:postgresql://localhost:5432/demo_markdown}
    username: ${DASH_DATABASE_USER:postgres}
    password: ${DASH_DATABASE_PASS:postgres}

  mail:
    host: ${DASH_MAIL_HOST:localhost}
    port: ${DASH_MAIL_PORT:1025}
    # 画像圧縮結果の送付先
    to: ml-rp-aws-admin@rakus.co.jp
    # メール送信元メールアドレス
    from: info@mail.rplearn.net
    mail-notification: noreply@mail.rplearn.net
    contact: 人材開発部  育成課  西上原聡  satoshi.nishiuehara@rakus.co.jp
    

  #アップロード可能な容量を設定
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

# プロフィール画像設定上限サイズ
max-profile-image-size: 1MB

#定期実行の設定
#毎月１日にスケジュールを設定
#必要ない可能性あり、一時的にコメントアウトしています。必要なさそうであれば消す
#画像の圧縮処理に伴い、再度使用(v4.9.0~)
cron:
  compressed-image: 0 0 0 1 * *
  checked-reserve: 0 0 * * * *
  # delete-image-monthly-report: 0 0 0 2 * *
  # delete-image-article: 0 0 0 2 * *

#ユーザー登録時のメール送信設定フラグ
action:
  userRegistMailSend: false

#セッションタイムアウトの設定 timeout 3時間(10800秒)
server:
  servlet:
    session:
      timeout: 10800

logging:
  level:
    root: INFO
  file:
    name: /var/log/dash/dash.log
  logback:
    rollingpolicy:
      file-name-pattern: /var/log/dash/dash-%d{yyyy-MM-dd}.log.gz
      max-history: 30





